# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PBHeader.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ePBHeader.proto\"N\n\x08PBHeader\x12\x14\n\x0cmagic_number\x18\x01 \x02(\r\x12\x15\n\rversion_major\x18\x02 \x02(\r\x12\x15\n\rversion_minor\x18\x03 \x02(\r\"\xdb\x03\n\x0bPBResultSet\x12\x15\n\rtimestamp_sec\x18\x01 \x02(\r\x12\x16\n\x0etimestamp_usec\x18\x02 \x02(\r\x12\x0e\n\x06src_id\x18\x03 \x02(\r\x12\x10\n\x08\x62link_id\x18\x04 \x02(\r\x12)\n\x08position\x18\x05 \x01(\x0b\x32\x17.PBResultSet.PBPosition\x12\x0f\n\x07payload\x18\x06 \x01(\x0c\x12.\n\x0bsensor_data\x18\x07 \x01(\x0b\x32\x19.PBResultSet.PBSensorData\x12,\n\nrssi_entry\x18\x08 \x03(\x0b\x32\x18.PBResultSet.PBRSSIEntry\x1a&\n\x0cPBSensorData\x12\x16\n\x0e\x62\x61tterie_value\x18\x01 \x01(\x0c\x1ar\n\nPBPosition\x12 \n\nx_position\x18\x01 \x01(\x01:\x0c\x31.79769e+308\x12 \n\ny_position\x18\x02 \x01(\x01:\x0c\x31.79769e+308\x12 \n\nz_position\x18\x03 \x01(\x01:\x0c\x31.79769e+308\x1a\x45\n\x0bPBRSSIEntry\x12\x11\n\tanchor_id\x18\x01 \x02(\r\x12\x0f\n\x07\x63hannel\x18\x02 \x02(\r\x12\x12\n\nrssi_value\x18\x03 \x02(\r')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PBHeader_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_PBHEADER']._serialized_start=18
  _globals['_PBHEADER']._serialized_end=96
  _globals['_PBRESULTSET']._serialized_start=99
  _globals['_PBRESULTSET']._serialized_end=574
  _globals['_PBRESULTSET_PBSENSORDATA']._serialized_start=349
  _globals['_PBRESULTSET_PBSENSORDATA']._serialized_end=387
  _globals['_PBRESULTSET_PBPOSITION']._serialized_start=389
  _globals['_PBRESULTSET_PBPOSITION']._serialized_end=503
  _globals['_PBRESULTSET_PBRSSIENTRY']._serialized_start=505
  _globals['_PBRESULTSET_PBRSSIENTRY']._serialized_end=574
# @@protoc_insertion_point(module_scope)
